<?php

use Illuminate\Database\Seeder;

class PagesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pages')->delete();
        
        \DB::table('pages')->insert(array (
            0 => 
            array (
                'id' => 2,
                'user_id' => 1,
                'title' => 'Term and Condition',
                'alt_name' => 'term-and-condition',
            'content' => '<p>Escape Media Group, Inc. ("EMG") provides users ("Users") of the web pages located at lalaplus.com, twisten.fm, and tinysong.com, and their associated subdomains including but not limited to widgets.lalaplus.com, beluga.lalaplus.com and listen.lalaplus.com, (the "Site") with a free platform for the discovery and promotion of music, the sharing of information and comments about music, communication with other Users, the posting, syndication of, linking to or uploading of User Content (defined below), social networking, the Application Programming Interface (API) and other features, functions, or services on the Site (collectively, the "Service"). The Service will include the cataloging, indexing, sharing and streaming of User Content.</p>
<p>This Agreement sets out the legally binding terms between you and EMG. This Agreement applies to all Users of the Service, including users who listen to or share audio content and or its associated metadata, information, and other materials or services on the Site. This Agreement applies to all Users regardless of if they are using the Service anonymously or as a registered user. If you choose to use the Service, you will be agreeing to abide by all of the terms and conditions of this Terms and Conditions of Use Agreement (the "Agreement"). EMG may, in its sole discretion, change, add or remove portions of this Agreement at any time, and by continuing to use the Service you agree to be bound by such revisions or modifications. If EMG does so, such changes will be posted on the Service, or sent to you via e-mail.</p>
<p>IF ANY OF THESE RULES OR ANY FUTURE CHANGES ARE UNACCEPTABLE TO YOU, DO NOT USE THE SERVICE. YOUR CONTINUED USE OF THE SERVICE NOW, OR FOLLOWING THE POSTING OF NOTICE OF ANY CHANGES IN THESE OPERATING RULES, WILL INDICATE ACCEPTANCE AND AGREEMENT BY YOU OF SUCH RULES, CHANGES, OR MODIFICATIONS.</p>
<p>EMG may change, suspend or discontinue any aspect of the Service at any time, including the availability of any Service feature, database, or content. EMG may also impose limits on certain features and services or restrict your access to parts or all of the Service without notice or liability.</p>
<p>In addition, when using particular EMG services, you and EMG shall be subject to any additional terms, guidelines or rules applicable to such services, which may be posted from time to time. All such additional terms, guidelines and rules are hereby incorporated by reference into this Agreement. Also, EMG may offer other services from time to time that are governed by different terms of service.</p>
<p>Unless explicitly stated otherwise, any new features that augment or enhance the current Service, including the release of new EMG properties, shall be subject to this Agreement.</p>
<p>Privacy</p>
<p>Your privacy is very important to EMG. Please review our&nbsp;<a href="http://lalaplus.com/#!/about/legal_privacy">Privacy Policy</a>, which also governs your use of the Service, to understand our practices.</p>
<p>&nbsp;</p>
<p>Intellectual Property</p>
<p>EMG is the owner of all intellectual property rights, including all copyrights, patents, trademarks associated with the Service, including all associated software, logos, text, and graphics, but excluding User Content (defined below). You agree not to display or use any EMG intellectual property without EMG\'s prior permission.</p>
<p>&nbsp;</p>
<p>License and Site Access</p>
<p>EMG grants you a limited license to access and make personal use of the Service. You agree not to download (other than page caching) or modify the Site, or any portion of it, except with express written consent of EMG. Any musical work made available via the Service is intended for Streaming only. Streaming meaning the transmission of an audiovisual work via the Internet from the Service to a user\'s device in such a manner that the data is intended for real-time listening and not intended to be copied, stored, permanently downloaded, or redistributed by the user. Accessing any musical work for any purpose or in any manner other than Streaming is expressly prohibited. This license does not include any resale or commercial use of the Site, the Service, or its contents; any downloading or copying of account information for the benefit of another merchant. The Service is for the personal use of Users only and may not be used in connection with any commercial endeavors except those may be specifically endorsed or approved by the management of EMG from time to time. Use of any automated script, program, and or mechanism to collect, scrape, retrieve, and or gather any information and or User Content from the Service is strictly prohibited without written consent for EMG.</p>
<p>Illegal and/or unauthorized use of the Service, including collecting usernames, email addresses or User Content of other Users by electronic or other means for the purpose of sending unsolicited email, unauthorized framing of or linking to the Site or other illegal purposes will be investigated. Commercial advertisements, affiliate links, and other forms of solicitation may be removed from posts or accounts without notice and may result in termination of membership privileges. EMG will take appropriate legal action for any illegal or unauthorized use of the Service. The Site, Service, or any portion thereof may not be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose without express written consent of EMG. You may not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information (including images, content, music, text, page layout, or form) of EMG and our affiliates or other Users. You may not use any meta tags or any other "hidden text" utilizing EMG\'s name or trademarks without the express written consent of EMG. Any unauthorized use terminates the permission or license granted by EMG. You are granted a limited, revocable, and nonexclusive right to create a hyperlink to the Service so long as the link does not portray EMG, its affiliates, or their products or services in a false, misleading, derogatory, or otherwise offensive manner. You may not use any EMG logo or other proprietary graphic or trademark as part of the link without express written permission.</p>
<p>&nbsp;</p>
<p>Account, Password, Security</p>
<ol>
<li>You will receive a password and account designation upon completing the Service\'s registration process. You are responsible for maintaining the confidentiality of the password and account, and are fully responsible for all activities that occur under your password or account. You agree to (i) immediately notify EMG of any unauthorized use of your password or account or any other breach of security, and (ii) ensure that you exit from your account at the end of each session. EMG cannot and will not be liable for any loss or damage arising from your failure to comply with this Section.</li>
<li>You agree to provide true, accurate, current and complete information about yourself as prompted by the Site\'s registration form (such information being the "Membership Data") and maintain and promptly update the Membership Data to keep it true, accurate, current and complete. If you do not, or EMG has reasonable grounds to suspect that you have not, EMG has the right to suspend or terminate your account and refuse any and all current or future us of the Service. Membership Data and certain other information about you are subject to our<a href="http://lalaplus.com/#!/about/legal_privacy">Privacy Policy</a>.</li>
</ol>
<p>&nbsp;</p>
<p>International</p>
<p>You agree to not use the Service or export any portion of the Service, including the User Content (defined below) in violation of U.S. export regulations. You are responsible for adhering to all relevant local and national laws wherever you are.</p>
<p>&nbsp;</p>
<p>Uploaded Content, Reviews, Comments, Etc.</p>
<p>Please choose carefully the words, information, content, messages, text, files, images, photos, videos, music, sounds, profiles, works of authorship or any other materials you post, upload, link to, publish, display or make available on the Site or through the Service and any such content that you provide or make available to other Users (collectively, "User Content"). You are responsible for all User Content, as set forth below.</p>
<p>EMG reserves the right, in its sole discretion, to reject, refuse to post, link to, or remove any User Content, or to restrict, suspend, or terminate your access to all or any part of the Site and/or the Service at any time, for any or no reason, with or without prior notice, and without liability. EMG has the right but not the obligation to remove or edit User Content, but does not regularly review User Content. EMG takes no responsibility and assumes no liability for any User Content.</p>
<p>By submitting User Content to the Service, you understand that it will be available to anyone in the world for streaming and viewing, that User Content submitted is being used for promotional and/or commercial purposes and that EMG will not be liable for any royalties to you or any other rights-holder of the Content. You understand that any uploaded material will stay up indefinitely on the Service; however, you may always reach back out and we will assist in its removal.</p>
<p>For clarification purposes, you retain all of your ownership rights in your User Content. However, unless EMG indicates otherwise, by submitting User Content to the Service you grant EMG and its affiliates a nonexclusive, royalty-free, perpetual, irrevocable, and fully sublicensable right to use, display, perform, reproduce, publish, and distribute such User Content throughout the world via the Service. You also grant each user of the Service a non-exclusive license to access your User Content through the Service, and to use, reproduce, distribute, display and perform such User Content as permitted through the functionality of the Service and under this Agreement. You grant EMG and it affiliates the right to use the name that you submit in connection with such User Content.</p>
<p>EMG may use your marks and name to promote (i) the User Content, the Site and the Services, and (ii) EMG\'s relationship with you and any associated labels and distributors. In addition, EMG may include your marks and names in EMG\'s advertising, publicity and promotion materials. EMG\'s use of your marks and names will not create any right, title or interest in or to your marks or names, and all such use and goodwill associated therewith will inure solely to your benefit, as the case may be. You are solely responsible for any necessary payments that may become due to any third parties as the result of your uploading, posting of or linking to the User Content and EMG\'s use thereof.</p>
<p>You agree that User Content you submit to the Service will not be illegal, obscene, threatening, defamatory, invasive of privacy, infringing of intellectual property rights, or otherwise injurious to third parties or objectionable. The following is a partial list of the kind of User Content that is illegal or prohibited on the Service. Prohibited User Content includes but is not limited to content that: (i) is obscene, patently offensive, or promotes racism, bigotry, hatred or physical harm of any kind against any group or individual; (ii) harasses or advocates harassment of another person; (iii) involves the transmission of "junk mail", "chain letters," or unsolicited mass mailing or "spamming"; (iv) consists of information that you know is false or misleading or promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous; (v) consists of an illegal or unauthorized copy of a copyrighted work, such as sound recordings, musical compositions and videos in which you do not personally own the copyright (including CDs and tracks you may have purchased), unless you are otherwise legally entitled or have the necessary authority or permission from the copyright owner(s) to submit the material and to grant to EMG all of the license rights granted herein; (vi) computer programs or links to them or providing information to circumvent manufacturer-installed copy-protect devices; (vii) contains restricted or password-only access pages or hidden pages or images (those not linked to or from another accessible page); (viii) provides material that exploits people under the age of 18 in a sexual or violent manner, or solicits personal information from anyone under 18; (ix) provides instructional information about illegal activities such as making or buying illegal weapons, violating someone\'s privacy, or providing or creating computer viruses; (x) solicits passwords or personal identifying information for commercial or unlawful purposes from other users; (xi) involves commercial activities and/or sales without our prior written consent such as contests, sweepstakes, barter, advertising, or pyramid schemes; or (xii) uses sexually suggestive imagery or any other unfair, misleading or deceptive content intended to draw traffic to the profile. EMG reserves the right to investigate and take appropriate legal action in its sole discretion against anyone who violates this provision, including without limitation, removing the offending User Content from the Service and terminating the membership of such violators.</p>
<p>Should EMG discover or be informed that you have posted User Content for which you do not personally own the copyright or otherwise do not have the necessary authority from the copyright owner, EMG may take all appropriate steps to rectify your noncompliance, including without limitation, disabling your ability to upload User Content to the Service, unless you provide EMG with a counter notification of your right to upload such User Content in compliance with our&nbsp;<a href="http://lalaplus.com/#!/about/legal_dmca">Copyright Policy</a>. Should EMG discover or be informed that you continue to upload User Content for which you do not personally own the copyright or otherwise do not have the necessary authority from the copyright owner after EMG has made reasonable efforts to disable your ability to do so, you will be considered a repeat infringer, and EMG will terminate your account and delete all data associated with your account; remove all of the User Content you have uploaded/submitted to the Site; and use its reasonable efforts to prohibit you from signing up for another User account in the future. If at any time you reasonably believe that you do not have, or no longer have the rights necessary to authorize EMG to make available certain User Content, then you shall notify EMG immediately so that EMG may make commercially reasonable efforts to remove the content from the Service.</p>
<p>EMG shall take reasonable steps to promptly notify you via the email address submitted by you upon registration with the Site for the Services should your ability to upload User Content to the Service be disabled and/or your account for the Service be terminated. If you believe that you do have the appropriate rights to post User Content, you can contact us in accordance with our&nbsp;<a href="http://lalaplus.com/#!/about/legal_dmca">Copyright Policy</a>.</p>
<p>When applicable, as between the parties, (i) you shall bear all responsibility for securing, administering and paying, on a timely basis, all publishing rights and royalties (including without limitation, synchronization fees owed to publishers or other applicable entities that own or control the copyrights to musical compositions), (ii) you shall bear all responsibility for paying all record royalties and license fees due to any artists, producers or other third-parties and all union, guild or other third party fees that may be required by contract or the Copyright Act by virtue of the use, copying and distribution of the User Content via the Service pursuant to this Agreement, and (iii) you shall bear all responsibility for paying all publishing rights due to any songwriters, composers, authors, publishers or third-parties that may be required by contract or the Copyright Act by virtue of the use, copying and distribution of the User Content via the Service pursuant to this Agreement. Furthermore, You shall bear sole responsibility for securing, administering and paying, on a timely basis, all public performance royalties for the User Content you submit.Unless specifically asked by EMG in the registration process, do not post the following items to the Service: telephone numbers or street addresses. You may not provide a false email address, impersonate any person or entity, or otherwise mislead as to the origin of any User Content.</p>
<p>Any photographs posted by you may not contain nudity or obscene, lewd, excessively violent, harassing, sexually explicit or otherwise objectionable subject matter. Information or User Content provided by other Users may contain inaccurate, inappropriate or offensive material, products or services, and EMG assumes no responsibility or liability for this material.</p>
<p>&nbsp;</p>
<p>Conduct</p>
<p>You agree to abide by the terms of this Agreement, and to not use the Service to: (i) interfere with, manipulate, or take any actions that may undermine the integrity of any rating system used on the Service; (ii) interfere with or disrupt the Service or servers or networks connected to the Service, or disobey any requirements, procedures, policies or regulations of networks connected to the Service; (iii) collect or store personal data about other Users; (iv) harass, abuse, or harm another person, or in order to contact, advertise to, solicit, or sell to any other User without their prior explicit consent; or (v) reverse engineer or decompile any elements of the Service except to the extent you may be expressly permitted to decompile under applicable law, it is essential to do so in order to achieve operability of the Service with another software program, and you have first requested EMG to provide the information necessary to achieve such operability and EMG has not made such information available.</p>
<p>Without limiting other remedies, EMG and its affiliates may immediately warn Users of your actions, issue a warning, temporarily suspend, indefinitely suspend or terminate your membership and refuse to provide the Service to you if: (i) you breach this Agreement or the documents it incorporates by reference; (ii) we are unable to verify or authenticate any information you provide to us; or (iii) we believe that your actions may cause financial loss or legal liability for you, us or our Users. Your membership will be terminated and you will be denied access to the Service if you breach this Agreement or any other agreement between you and EMG in any way on more than one occasion.</p>
<p>You are solely responsible for your interactions with other Users of the Service. EMG reserves the right, but has no obligation, to monitor disputes between you and other Users.</p>
<p>&nbsp;</p>
<p>Lala+ Rewards</p>
<p>You may elect to participate in the Lala+ Rewards program ("Lala+ Rewards"). Lala+ Rewards is a service under which you can acquire points and redeem those points for certain online services and digital products. You can earn points by completing surveys provided by EMG and by various third-party companies.</p>
<p>Points have no monetary value. You may not obtain any cash or money in exchange for points, regardless of how you acquired those points. Points are not your personal property. Your only recourse for using points is to redeem them through www.lalaplus.com. We encourage you to redeem your points. The existence of a particular offer available for points redemption is not a commitment by us to maintain or continue to make the offers in the future. The scope, variety and type of online services and digital products that you may obtain by redeeming points can change at any time and without notice to you. We have no obligation to continue making offers available for points redemption. You can see how many points you have accrued by checking your points balance on your User profile.</p>
<p>Points may expire at any time. We may cancel, suspend or otherwise limit your access to your points balance if we suspect fraudulent, abusive or unlawful activity on your points balance. We retain the right to determine what conduct shall result in cancellation of your points balance. Once we delete points from a balance, we will not reinstate them, except at our discretion. When we cancel, suspend or otherwise limit access to your points balance, your right to use your points balance immediately ceases. We will use reasonable efforts to investigate points balances that are subject to access limitations and to reach a final decision on the limitations promptly. In addition, we may limit your use of the points service, including applying limits to: the number of points you may have credited to your points balance at one time, the number of points you may redeem within a given time period (for example, one day), and the number of promotion points you may obtain in a single event.</p>
<p>If we post points to your balance for an activity that is subsequently voided, canceled or involves a returned item, then we will remove those points from your balance. You are responsible for any tax consequences that may result from your participation in Lala+ Rewards.</p>
<p>EMG may discontinue the Lala+ Rewards program at any time. Upon the cancellation of the program, any points accrued and not redeemed by you will be deleted.</p>
<p><br /><a name="giftCards"></a></p>
<p>Gift Cards &amp; Promotional Codes</p>
<ol>
<li>
<ol>
<li>Gift Subscriptions are pre-paid upgrades to the premium versions of the Lala+ service redeemable at www.lalaplus.com.</li>
<li>There are no refunds, exchanges or other credit for Gift Subscriptions that are not redeemed.</li>
<li>Gift Subscriptions do not expire.</li>
<li>Gift Subscriptions are valid only for credit towards the premium versions of the Lala+ service and are not valid for any other products or services offered by Lala+.</li>
<li>Lala+ is not responsible if the Gift Subscription is lost, stolen or used without permission.</li>
<li>Gift Subscriptions are not redeemable or refundable for cash, subject to applicable law, and cannot be resold or combined with any other special or free offers, including other Gift Subscriptions and Gift Cards.</li>
<li>Gift Subscriptions are issued by Escape Media Group, Inc., a Delaware corporation. Gift Subscriptions purchased at www.lalaplus.com are valid for redemption only at www.lalaplus.com.</li>
</ol>
</li>
</ol>
<p>Gift Subscriptions and their use are subject to these terms and the Lala+ Terms of Use. These Gift Subscription terms are governed by the laws of the State of New York, excluding its conflict of law principles, and are subject to change without notice.</p>
<p>&nbsp;</p>
<p>Use &amp; Storage</p>
<p>You acknowledge that EMG may establish general practices and limits concerning use of the Service, including without limitation the maximum number of days that User Content will be retained by or made available through the Service, the maximum disk space that will be allotted on EMG\'s servers on your behalf, and the maximum number of times (and the maximum duration for which) you may access the Service in a given period of time. You agree that EMG has no responsibility or liability for the blocking, deletion or failure to store any User Content maintained or transmitted by the Service. You acknowledge that EMG reserves the right to cancel accounts that are inactive for an extended period of time. You further acknowledge that EMG reserves the right to change these general practices and limits at any time, in its sole discretion, with or without notice.</p>
<p>&nbsp;</p>
<p>Third-Party Content, Links and Syndication</p>
<p>EMG is not responsible for any User Content, third-party content, syndicated content, applications, services, advertisements, and/or links that may be contained in the Service. The Service may contain links to third party websites that are not owned or controlled by EMG. EMG has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party websites. In addition, EMG will not and cannot censor or edit the content of any third-party site. By using the Service, you expressly relieve EMG from any and all liability arising from your use of any third-party website. Accordingly, we encourage you to be aware when you leave the Site and to read the terms and conditions and privacy policy of each other website that you visit. Any correspondence, business dealings with, syndication, linking or participation in promotions of third parties found on or through the Service, including payment or delivery of related goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such third parties. EMG has no control over third-party websites or resources, and as such, you acknowledge and agree that EMG is not responsible for their availability, reliability, or functionality, and does not endorse and is not responsible or liable for any third-party content, applications, services, advertising, products, or other materials on or available from such websites or resources. EMG shall not be responsible or liable for any loss or damage of any sort incurred as the result of any dealings between you and any third parties, or as the result of the presence of such third-party content or User Content on the Service or as a result of the failure of such third-party services, applications, or content to function as intended.</p>
<p>&nbsp;</p>
<p>Termination</p>
<p>You may terminate this Agreement at any time by permanently discontinuing your use of the Service and Service. EMG may terminate this Agreement at any time for any reason upon notice to you by email. Sections 3, 12, 13, 14, 15, 16, 17 and 18 shall continue in full force and effect upon any termination of this Agreement.</p>
<p>&nbsp;</p>
<p>Representations &amp; Warranties</p>
<p>You represent and warrant that you have the full authority to act on your behalf and on behalf of any and all owners of any right, title and interest in and to any User Content you post, submit, transfer, make available, or link to. You represent and warrant that you are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations and warranties set forth in this Agreement, and to abide by and comply with this Agreement and have obtained all necessary third-party consents, approvals, authorizations, licenses and permissions necessary to enter into and fully perform your obligations herein. In any case, you affirm that you are over the age of 13, as the Service is not intended for children under 13. If you are under 13 years of age, then please do not use the Service. Your membership or access to the Service may be deleted or blocked without warning if it is found that you are misrepresenting your age. Your membership is solely for your personal use, and you shall not authorize others to use your account.</p>
<p>You represent and warrant that you are solely responsible for all User Content posted, uploaded, published, made available or displayed through your User account, including any messages, and for your interactions with other Users. You shall be solely responsible for your own User Content and the consequences of posting or publishing it. In connection with User Content, you affirm, represent, and warrant that: (i) you own or have, and will own or have during the term the necessary licenses, rights, consents, and permissions to use and authorize EMG to use all patent, trademark, trade secret, copyright or other proprietary rights in and to any and all User Content to enable inclusion and use of the User Content in the manner contemplated by the Service and these Terms of Service; (ii) you have the written consent, release, and/or permission of each and every identifiable individual person in the User Content to use the name or likeness of each and every such identifiable individual person to enable inclusion and use of the User Content in the manner contemplated by the Service and these Terms of Service; (iii) you will be responsible for the payment of any and all royalties required by any composer, publisher or owner of the underlying musical composition(s) embodied in the User Content, all license fees, and record royalties to artists and all union, guild or other third-party fees that may be required by contract or the Copyright Act that may be due by virtue of the exploitation of the User Content through the Service as authorized hereunder. For clarity, you retain all of your ownership rights in your User Content.</p>
<p>You represent and warrant that you shall not act in any manner that conflicts or interferes with any existing commitment or obligation of yours, and that no agreement previously entered into by you will interfere with your performance of your obligations under this Agreement.</p>
<p>You represent and warrant that you shall perform in compliance with any applicable laws, rules and regulations of any governmental authority.</p>
<p>You represent and warrant that you will not use the Service to upload, post, link to, email, transmit, or otherwise make available any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy, or limit the functionality of any computer software or hardware or any telecommunications equipment.</p>
<p>&nbsp;</p>
<p>Disclaimer</p>
<p>YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK. THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. EMG EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. EMG MAKES NO WARRANTY THAT (i) THE SERVICE WILL MEET YOUR REQUIREMENTS, (ii) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (iii) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE OR RELIABLE, (iv) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR EXPECTATIONS, AND (v) ANY ERRORS IN THE SOFTWARE WILL BE CORRECTED. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM EMG OR THROUGH OR FROM THE SERVICE SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THIS AGREEMENT.</p>
<p>&nbsp;</p>
<p>Indemnification, Limited Liability</p>
<p>You hereby indemnify and hold harmless, and upon EMG\'s request, defend, EMG its affiliates (and their respective directors, officers and employees) from and against any and all losses, liabilities, damages, costs or expenses (including reasonable attorneys\' fees and costs) arising out of any claim, action, or proceeding brought by a third party based on: (i) a breach of any warranty, representation, covenant or obligation of yours under this Agreement; or (ii) any allegation that any User Content provided, uploaded, syndicated, linked to or authorized by or on behalf of you hereunder or EMG\'s or any User\'s use thereof violates or infringes the rights of another party. You will reimburse EMG and its affiliates on demand for any actual payments made in resolution of any liability or claim that is subject to indemnification under this Section 14, provided that EMG obtains your written consent prior to making such payments, such consent not to be unreasonably withheld, delayed or conditioned. EMG shall promptly notify you of any such claim, and you shall assume control of the defense of such claim upon EMG\'s request. EMG shall have the right, at its expense, to participate in the defense thereof under your direction.</p>
<p>EXCEPT PURSUANT TO YOUR INDEMNITY OBLIGATION IN SECTION 14(a), AND EXCEPT FOR A BREACH OF YOUR REPRESENTATIONS AND WARRANTIES IN SECTION 12, IN NO EVENT SHALL EITHER PARTY BE LIABLE TO THE OTHER PARTY FOR INDIRECT, INCIDENTAL, CONSEQUENTIAL OR SPECIAL DAMAGES, INCLUDING LOSS OF PROFITS OR PUNITIVE DAMAGES, EVEN IF ADVISED OF THEIR POSSIBILITY. NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, EMG\'S LIABILITY TO YOU FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO AMOUNT PAID, IF ANY, BY YOU TO EMG FOR THE SERVICE DURING THE TERM OF MEMBERSHIP.</p>
<p>&nbsp;</p>
<p>Applicable Law</p>
<p>This Agreement and the relationship between you and EMG shall be governed by the laws of the State of New York without regard to its conflict of law provisions. You and EMG agree to submit to the personal and exclusive jurisdiction of the courts located within the State and County of New York.</p>
<p>&nbsp;</p>
<p>Notice</p>
<p>Except as explicitly stated otherwise, any notices to EMG shall be sent by certified mail, return receipt requested, to Escape Media Group, Inc., 201 SE 2nd Avenue, Suite 201, Gainesville, Florida 32601, Attn: Legal Department. Notice shall be deemed given three (3) days after the date of mailing.</p>
<p>&nbsp;</p>
<p>Copyright Infringement</p>
<p>EMG respects the intellectual property of others, and we ask our Users to do the same. If you believe that your work has been copied or used in a way that constitutes copyright infringement, or your intellectual property rights have been otherwise violated, please provide EMG\'s copyright agent with the following information ("Notice"): (1) an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright or other intellectual property interest; (2) a description of the copyrighted work or other intellectual property that you claim has been infringed; (3) a hyperlink to the material that you claim is infringing on the Service. Please note, providing a song, artist, or album name is not sufficient, you must provide a unique hyperlink to each item of material that you claim is infringing on the Service ; (4) your address, telephone number, and email address; (5) a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and (6) a statement by you, made under penalty of perjury, that the above information in your Notice is accurate and that you are the copyright or intellectual property owner or authorized to act on the copyright or intellectual property owner\'s behalf. Any Notice of claims of copyright or other intellectual property infringement must be sent to EMG at:</p>
<p>&nbsp;</p>
<p>Colin Hostert</p>
<p>Copyright Agent<br />EMG Legal Department</p>
<p>Please note that this procedure is exclusively for notifying EMG and its affiliates that your copyrighted material has been infringed.</p>
<p>&nbsp;</p>
<p>General</p>
<p>This Agreement along with the&nbsp;<a href="http://lalaplus.com/#!/about/legal_privacy">Privacy Policy</a>&nbsp;and any additional terms, rules or regulations posted on the Service constitute the entire agreement between you and EMG and govern your use of the Service, superseding any prior agreements between you and EMG. You also may be subject to additional terms and conditions that may apply when you use affiliate services, third-party content or third-party software.</p>
<p>The failure of EMG to exercise or enforce any right or provision of this Agreement shall not constitute a waiver of such right or provision.</p>
<p>If any provision of this Agreement is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties\' intentions as reflected in the provision, and the other provisions of this Agreement remain in full force and effect.</p>
<p>You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Service or this Agreement must be filed within one (1) year after such claim or cause of action arose or be forever barred.</p>
<p>The section titles in this Agreement are for convenience only and have no legal or contractual effect.</p>',
                'meta_title' => 'Term and Condition',
                'meta_description' => 'Term and Condition',
                'meta_keywords' => 'term, condition',
                'created_at' => '2018-07-21 14:31:12',
                'updated_at' => '2020-07-15 02:28:16',
            ),
            1 => 
            array (
                'id' => 3,
                'user_id' => 1,
                'title' => 'About Us',
                'alt_name' => 'about-us',
                'content' => '<h3><strong>Our story</strong></h3>
<p>It was 2007 when 23-year-old Ni Na began working on a project to simplify music access for her friends.</p>
<p>Working initially from his Paris bedroom, Daniel soon recognised the potential of his idea and gathered a small team together. It didn\'t take long for investors and music labels to catch on. Today Deezer is available in more than 180 countries, partnering with thousands of independent and major labels, with one of the largest catalogues out there (53 million tracks and counting).</p>
<p>We combine human recommendations from the Deezer Editors with smart technology to help people discover music they\'ll love. Everyone can enjoy unlimited music on mobile and web, while Deezer Premium subscribers benefit from music as well as entertainment and sports on demand on all devices, without ads, in enhanced audio quality.</p>
<p>The adventure continues...</p>',
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'created_at' => '2019-07-21 14:31:12',
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 4,
                'user_id' => 1,
                'title' => 'Privacy Policy',
                'alt_name' => 'privacy-policy',
            'content' => '<p>Lala+ has established a comprehensive Privacy Policy ("the Policy") which is designed to help protect your privacy rights. By using the Lala+ Service, you, the user, agree to the terms of the Policy. The following bullet points are an overview of our Policy and the significant control you have over how your data is shared:</p>
<ul>
<li>You may opt-out of the collection of information associated with you, or limit its use and disclosure, by going to&nbsp;<a href="http://www.networkadvertising.org/managing/opt_out.asp" target="_blank" rel="noopener">http://www.networkadvertising.org/managing/opt_out.asp</a>.</li>
<li>Your Personally Identifiable Data and Protected Private Information will never be sold to third parties.</li>
<li>While no system can be perfect, we have secure systems in place to protect your sensitive Private Information.</li>
<li>If you have any inquiries, complaints, or concerns about the collection, protection and dissemination of your data, please access the&nbsp;<a href="http://lalaplus.com/#!/about/contact">Contact page</a>&nbsp;to find our contact information.</li>
</ul>
<p>Please read the Privacy Policy below for a full treatment.</p>
<p>Privacy Policy</p>
<p>Lala+ is provided by Escape Media Group Inc ("EMG"). EMG collects information about you when you use lalaplus.com, associated subdomains including but not limited to widgets.lalaplus.com, beluga.lalaplus.com and listen.lalaplus.com (the "Site"). Once collected, there are certain parties with whom EMG may selectively share this information. Collectively, the Site and the API ("API" is the Lala+ Application Programming Interface, accessible through http://developers.lalaplus.com) are hereby referred to as the "Service."</p>
<p>If you would like to opt-out of the collection of your Personally Identifiable Information, please email&nbsp;<a href="mailto:Support@lalaplus.com">support@lalaplus.com</a>. If you find any part of the Policy unacceptable, please discontinue your use of the Site immediately, as this Policy is integrated into, and subject to the&nbsp;<a href="http://lalaplus.com/#!/about/legal_terms">Terms of Service</a>&nbsp;for the use of the Site and the&nbsp;<a href="http://lalaplus.com/#!/about/legal_terms">Terms of Service</a>&nbsp;for the usage of the API. Your use of any or all components of the Service, including but not limited to the Site and the API, constitutes a knowing acceptance and agreement to the terms and provisions of the Policy.</p>
<p>Lala+ has been awarded TRUSTe\'s Privacy Seal signifying that this privacy policy and the practices set forth herein have been reviewed by TRUSTe for compliance with&nbsp;<a href="http://www.truste.com/privacy_seals_and_services/consumer_privacy/privacy-programs-requirements.html" target="_blank" rel="noopener">TRUSTe\'s program requirements</a>&nbsp;including transparency, accountability and choice regarding the collection and use of your personal information. The TRUSTe program does not cover information that may be collected through downloadable software or that you voluntarily provide to third-parties through lalaplus.com. TRUSTe\'s mission, as an independent third party, is to accelerate online trust among consumers and organizations globally through its leading privacy trustmark and innovative trust solutions. If you have questions or complaints regarding our privacy policy or practices, please contact us at&nbsp;<a href="mailto:Support@lalaplus.com">support@lalaplus.com</a>. If you are not satisfied with our response you can contact TRUSTe&nbsp;<a href="http://watchdog.truste.com/pvr.php?page=complaint" target="_blank" rel="noopener">here</a>.</p>
<p>1. Definitions</p>
<ul>
<li>User: For the purposes of the Policy, a user shall be defined as someone who is either directly interacting with the service or someone who is interacting with the service via any third party who is using the API.</li>
<li>Personally Identifiable Information: Unencrypted data that encompasses a user\'s email address, address of residence, or phone number.</li>
<li>Public Information: Data which a user has submitted to the Service, or has been accumulated by the Service through its use, and is available to be viewed and/or consumed by any user of the Service or the general public. This may include, but is not necessarily limited to playlists, tags, comments made through your Facebook or Twitter login, listening history, a user\'s combined first and last name, and/or information accessible on a user\'s public profile.</li>
<li>Anonymous Information: Data which a user has submitted to the Service, or has been accumulated by the Service, that is not reasonably able to be connected to or associated with any Personally Identifiable Information.</li>
<li>Protected Private Information: Data which consists of Paypal username, Paypal password, credit card number, credit card expiration date, credit card CSC, credit card type, and password (plain text or encrypted)</li>
</ul>
<p>2. Information we collect and who can access it:</p>
<ul>
<li>Public Information: To provide the needed data to make the Service possible, EMG collects and stores information that includes, but is not necessarily limited to:
<ul>
<li>User information submitted to register for our Service;</li>
<li>Information entered into user profiles;</li>
<li>Music library information (as well as accompanying information such as tags, ratings, usage data, and comments);</li>
<li>Information submitted to polls, contests, surveys, or other features of the Service, or information about when you respond to offers or advertisements on the Service;</li>
</ul>
In addition, EMG stores and in some cases displays this information as necessary to fulfill our legal obligations, resolve disputes, and enforce our agreements. EMG may provide third parties with Public information about users as long as it is not Personally Identifiable Information or Protected Private Information.</li>
<li>Public Information and the API: EMG may share Public Information (excluding any Personally Identifiable Information) via the API.</li>
<li>Personally Identifiable Information: EMG collects, stores, and in some cases displays Personally Identifiable Information within the Service. This information is needed to enable certain features the Service provides, and is stored for as long as you have an account, and as necessary to fulfill our legal obligations, resolve disputes, or enforce our agreements. Personally Identifiable Information, such as a user\'s email address, address of residence, or phone number, will not be shared with any third party without consent from the user unless otherwise stated in this policy or the Terms of Service.</li>
<li>You should also be aware that if you voluntarily disclose personally identifiable information on openly viewable parts of the service, that information can be viewed publicly and can be collected and used by third parties without our knowledge and may result in unsolicited messages from other individuals or third parties. Such activities are beyond the control of EMG and this Policy.</li>
<li>Access to Personally Identifiable Information: If your personally identifiable information changes you may update it as necessary. If or you no longer desire our service, you may deactivate your account by making the change on our member information page, emailing us at&nbsp;<a href="mailto:support@lalaplus.com">support@lalaplus.com</a>, or by contacting us by email or postal mail at the contact information listed below. We will respond to your request to access within 30 days.</li>
<li>Data Retention: We will retain your information for as long as your account is active or as needed to provide you services. If you wish to cancel your account or request that we no longer use your information to provide you services contact us at&nbsp;<a href="mailto:support@groovehshark.com">support@groovehshark.com</a>. We will retain and use your information as necessary to comply with our legal obligations, resolve disputes, and enforce our agreements.</li>
<li>Personally Identifiable Information and the API: Certain features in the Service may allow for or be introduced to allow for integration between the Service and other third party services. In order for some features to be provided, some Personally Identifiable Information may need to be transferred between EMG and the third party who is using the service.</li>
<li>Should you utilize any feature or piece of functionality in the Service and (A) provide your username and/or password to a third party service, such as a credit card processor, or (B) authorize the exchange of data from the third party service to the Service via the third parties website, API, or product, you authorize EMG to share your Personally Identifiable Information with such a third party service with the exception of any Protected Private Information which will not be shared.</li>
<li>Anonymous information: EMG records anonymous information about users of the service, which is stored as necessary to fulfill our legal obligations, resolve disputes, and enforce our agreements. This information does not link any statistic with any particular user. This data may include, but is not limited to, averages and or totals of browser and operating system types, entry and exit pages, user, artist, or album popularity, demographic information, and amount of data transferred. This information may be shared with any third party EMG chooses at any time and for any length of time (including making this data available via the API).</li>
<li>IP Address Information: When you use the Site and/or Service, the IP Address of the computer or network device making the request is stored. IP address information is stored for no more than six months from the date the information is recorded. This data may be stored for longer, as necessary to fulfill our legal obligations, resolve disputes, and enforce our agreements, if EMG is so ordered to do so by a United States court of law with proper jurisdiction. This may be done without any notification to the user. This information may also be kept longer than six months by EMG if a user is found in EMG\'s judgment to be suspect of carrying out illegal, unlawful, or dangerous activity with or within the Site and/or the Service.</li>
<li>Newsletters: If you wish to subscribe to our newsletter(s), we will use your name and email address to send the newsletter to you. Out of respect for your privacy, we provide you a way to unsubscribe. Please see the "Choice and Opt-out" section below.</li>
<li>Choice/Opt-Out: You may choose to stop receiving our newsletter or marketing emails by following the unsubscribe instructions included in these emails or you can contact us at&nbsp;<a href="mailto:support@groovehshark.com">support@lalaplus.com</a>&nbsp;or you may update your settings within your profile.</li>
<li>Facebook Connect: You can log in to our site using sign-in services such as Facebook Connect provider. These services will authenticate your identity and provide you the option to share certain personal information with us such as your name and email address to pre-populate our sign up form. Services like Facebook Connect give you the option to post information about your activities on this Web site to your profile page to share with others within your network.</li>
<li>Tell-A-Friend: If you choose to use our referral service to tell a friend about our site, we will ask you for your friend\'s name and email address. We will automatically send your friend a one-time email inviting him or her to visit the site. Escape Media Group stores this information for the sole purpose of sending this one-time email and tracking the success of our referral program. Your friend may contact us at&nbsp;<a href="mailto:support@groovehshark.com">support@lalaplus.com</a>&nbsp;to request that we remove this information from our database.</li>
<li>Legal Disclosure: We may also disclose your personal information:</li>
<li>a) as required by law, such as to comply with a subpoena, or similar legal process</li>
<li>b) when we believe in good faith that disclosure is necessary to protect our rights, protect your safety or the safety of others, investigate fraud, or respond to a government request,</li>
<li>c) to any other third party with your prior consent to do so.</li>
<li>If you, the user, object to the above treatment of your information, then please follow this&nbsp;<a href="http://www.networkadvertising.org/managing/opt_out.asp" target="_blank" rel="noopener">link</a>&nbsp;to opt-out of the collection of your information, which may result in limited access to the Site and/or the Service. If you are a user residing in the European Economic Area ("EEA") or Switzerland ("CH") (together "EEA/CH"), please see section 11 for additional information relating to the treatment of your information.</li>
</ul>
<p>3. Advertising</p>
<ul>
<li>Advertisers are not given special access to a user\'s Personally Identifiable Information unless otherwise stated in this Policy or the Terms of Service. If you choose to follow an advertisement link, you do so at your own risk. EMG does not guarantee the safety or accuracy of any third party site, advertisement, or product. Advertisers also have their own privacy policies and terms of service that must be carefully reviewed.</li>
<li>The Service may use "cookie" technology to collect website usage data and make your advertising more relevant. You can remove or block cookies by altering your browser\'s cookie settings. The Service may also use "flash cookie" technology as part of the music player to store User preferences and session information.</li>
<li>We may partner with third party advertisers who may (themselves or through their partners) place or recognize a unique cookie on your browser. These cookies enable more customized ads, content or services to be provided to you. No personally identifiable information is on, or is connected to, these cookies.</li>
<li>We may use the non-Personally Identifiable Information that we collect to customize and personalize the advertising and the content you see.</li>
<li>EMG may allow third parties to place cookies and/or other tracking technologies, such as web beacons, clear GIFs, and/or tracking pixels, on the Site for the purpose of allowing that third party to record that a user has visited the Site and/or used the Service, or to gather other information, provided that such a third party is doing so only to collect Anonymous Information that shall not include any Personally Identifiable Information. In some instances third-parties may request an encrypted or "hashed" (non-human readable) user identifier that may correspond to other information already obtained from another party on a particular user. To learn more about behavioral advertising or to opt-out of this type of advertising, you can also visit&nbsp;<a href="http://www.privacychoice.org/choose" target="_blank" rel="noopener">http://www.privacychoice.org/choose</a>,&nbsp;<a href="http://www.networkadvertising.org/" target="_blank" rel="noopener">http://www.networkadvertising.org</a>, and&nbsp;<a href="http://rt.displaymarketplace.com/optout.html" target="_blank" rel="noopener">http://rt.displaymarketplace.com/optout.html</a>.</li>
</ul>
<p>4. Surveys</p>
<ul>
<li>You may choose to answer surveys posed through lalaplus.com by EMG and/or a third party. This policy does not cover survey responses you provide to any third party. Survey responses you provide to EMG may be published, transferred, sold or licensed to third parties; however, no Personally Identifiable Information will be included with the survey responses except for that Personally Identifiable Information you provide as a survey response.</li>
</ul>
<p>5. Data Security</p>
<ul>
<li>EMG takes reasonable steps to protect information from loss, misuse, and unauthorized access, disclosure, alteration, and destruction. EMG has in place appropriate physical, electronic, and managerial procedures to safeguard and secure the information from loss, misuse, unauthorized access or disclosure, alteration, or destruction.</li>
<li>The security of your personal information is important to us. When you enter sensitive information (such as a credit card number) on our order forms, we encrypt the transmission of that information using secure socket layer technology (SSL).</li>
</ul>
<p>6. Enforcement</p>
<ul>
<li>EMG uses a self-assessment approach to ensure compliance with the Policy and Safe Harbor Principles. EMG periodically verifies that the Policy is accurate, accessible, and comprehensive as to issues regarding the user, prominently displayed, and completely implemented. We encourage users to address any inquiries, concerns, or complaints using the contact information listed on the Contact page. Upon such a request from an EEA/CH user, EMG will investigate and attempt to resolve any complaints and disputes regarding use and disclosure of information in accordance with the Principles of the Safe Harbor.</li>
<li>Only for use relating to data that is received by EMG from users residing in the EEA/CH ("EEA/CH data subjects"), if a complaint cannot be resolved through our internal process, EMG agrees to dispute resolution through an independent recourse mechanism. Lala+ complies with the EU Safe Harbor framework as set forth by the Department of Commerce regarding the collection, use, and retention of data from the European Union.</li>
</ul>
<p>7. Minors</p>
<ul>
<li>EMG does not knowingly collect or solicit Personally Identifiable Information from or about children under age 13 except as permitted by law. If we discover we have received any information from a child under 13 in violation of this policy, we will delete that information immediately. If you believe EMG has any information from or about anyone under 13, please contact us at&nbsp;<a href="mailto:privacy@escapemg.com">privacy@escapemg.com</a>.</li>
</ul>
<p>8. Forum Selection and Choice of Law</p>
<ul>
<li>This Policy, which is an agreement between you and EMG, shall be governed by the laws of the State of Colorado without regard to its conflict of law provisions. You and EMG agree to submit to the personal and exclusive jurisdiction of the courts located within the State and County of Colorado.</li>
</ul>
<p>9. Indemnification</p>
<ul>
<li>You, the user, hereby indemnify and hold harmless, and upon EMG\'s request, defend, EMG and its affiliates (and their respective directors, officers and employees) from and against any and all losses, liabilities, damages, costs or expenses (including reasonable attorneys\' fees and costs) arising out of any external party gaining access to and/or utilizing EMG\'s API in a way which violates EMG\'s API TOS.</li>
</ul>
<p>10. Privacy Policy Updates</p>
<ul>
<li>EMG is committed to protecting your privacy while providing you with a competitive and secure Service. As such, EMG will evaluate the terms of this Policy on a rolling basis and make necessary revisions to the Policy as new technology, law, and business concerns arise. Therefore, EMG may make periodic revisions or alterations to the Policy. EMG reserves the right to revise this agreement at any time, so please occasionally re-read this page; however, if material alterations occur, we will also provide Notice on our home page, by email, or by blog post. Nonetheless, any revisions will be posted to this page along with the most current date of revision.</li>
</ul>
<p>11. Contact</p>
<ul>
<li>If you have any inquiries, complaints, or concerns about the collection and dissemination of your data, please email us at&nbsp;<a href="mailto:support@lalaplus.com">support@lalaplus.com</a>. Inquiries can also be sent to our mailing address at 201 SE 2nd Ave. Suite 209, Gainesville, FL 32601.</li>
</ul>
<p>12. Notice of Safe Harbor Compliance</p>
<ul>
<li>For the personally identifiable information of users received from the European Economic Area ("EEA"), EMG is committed to handling such personal information in accordance with the U.S. Department of Commerce\'s Safe Harbor Principles. EMG\'s Safe Harbor certification can be found at&nbsp;<a href="http://safeharbor.export.gov/list.aspx" target="_blank" rel="noopener">http://safeharbor.export.gov/list.aspx</a>. For more information about the Safe Harbor Principles, please visit the U.S. Department of Commerce\'s Website at&nbsp;<a href="http://export.gov/safeharbor" target="_blank" rel="noopener">http://export.gov/safeharbor</a>.</li>
<li>EMG recognizes the European Union\'s comprehensive privacy and data protection legislation, the Directive on Data Protection 95/46/EC ("the Directive") which applies to the EEA. EMG also recognizes Switzerland\'s ("CH") Federal Act on Data Protection ("FADP"). Together, these data protection regimes ("EEA/CH") restrict companies and other organizations from transferring personal data from the EEA/CH to countries that do not meet mandated "adequacy standards" for when it is received in third party countries, such as the United States. Based on the commitments and assertions of the Policy, EMG hereby asserts compliance with the Principles of the Safe Harbor.</li>
<li>This Notice applies to EEA/CH data subjects.</li>
<li>EMG gives EEA/CH data subjects the option of being able to request access to your information profile so that you may correct, amend, or delete information.</li>
</ul>',
    'meta_title' => NULL,
    'meta_description' => NULL,
    'meta_keywords' => NULL,
    'created_at' => '2019-07-21 14:31:12',
    'updated_at' => '2019-08-13 19:45:54',
),
3 => 
array (
    'id' => 5,
    'user_id' => 1,
    'title' => 'Legal information',
    'alt_name' => 'legal-information',
    'content' => '<p>Music is a form of intellectual property protected and regulated by aspects of intellectual property law, including copyright laws and various licensing regulations. Together, these laws work to safeguard the rights of musicians, performers, producers, and others in the music industry as well as the music itself. A current issue in music law revolves around technological developments in online file-sharing systems that increase the prevalence of illegal distribution &ndash; that is, without the copyright owner&rsquo;s permission &ndash; of protected music. Music law attempts to address this and other issues related to the dissemination of music, and to reconcile the protection of the rights of artists with the rights of consumers. To learn more about the regulations governing the music industry and the field of music law, visit the links on this page.</p>',
    'meta_title' => NULL,
    'meta_description' => NULL,
    'meta_keywords' => NULL,
    'created_at' => '2019-07-21 14:31:12',
    'updated_at' => NULL,
),
4 => 
array (
    'id' => 6,
    'user_id' => 1,
    'title' => 'Cookies and Personal data',
    'alt_name' => 'cookies-and-personal-data',
    'content' => '<p>The EU law on the handling of personal data, The General Data Protection Regulation, is often referred to by its acronym GDPR.</p>
<p>How does the GDPR affect your website&rsquo;s use of cookies and online tracking? How do you comply? And how does it affect the cookie policy and your cookie consent on your website?</p>
<p>In this article, we give a comprehensive introduction to the GDPR and a hands-on guide as to what the rules mean for you and your website.</p>
<p>GDPR and cookies | What do I need to know? | Is my use of cookies compliant?</p>
<p><strong>GDPR and cookies</strong></p>
<p>The GDPR is a EU regulation that represents the most significant initiative on data protection in 20 years.</p>
<p>The purpose is to protect &ldquo;natural persons with regard to the processing of personal data and on the free movement of such data&rdquo;, e.g. the website user.</p>
<p>Cookies are mentioned once in the 88 pages long regulation. However, those few lines have a significant impact on the compliance of cookies:</p>
<p>(30): &ldquo;Natural persons may be associated with online identifiers [&hellip;] such as internet protocol addresses, cookie identifiers or other identifiers [&hellip;]. This may leave traces which, in particular when combined with unique identifiers and other information received by the servers, may be used to create profiles of the natural persons and identify them.&rdquo;</p>
<p>In other words: when cookies can identify an individual, it is considered personal data.</p>
<p><strong>What&rsquo;s the deal with cookies anyway?</strong></p>
<p>Cookies are small files that are automatically dropped on your computer as you browse the web. In and of themselves they are harmless bits of text that are locally stored and can easily be viewed and deleted.</p>
<p>But cookies can give a great deal of insight into your activity and preferences, and can be used to identify you without your explicit consent.</p>
<p>This represents a major breach from a legal point of view, and as data technologies grow more and more sophisticated, your privacy as a user is increasingly compromised.</p>
<p>Often, the cookies don&rsquo;t even originate from the website you are visiting, but from third parties that track you for marketing purposes. All of which is going on &ldquo;behind the scenes&rdquo;.</p>
<p>While not all cookies are used in a way that could identify users, the majority (and the most useful ones to the website owners) are, and will therefore be subject to the GDPR.</p>
<p>Cookies for analytics, advertising and functional services, such as survey and chat tools, are all examples of cookies that can identify users.</p>
<p>The problem with cookies is both one of privacy - what is being registered? - and one of transparency - who is tracking you, for what purpose, where does the data go, and for how long does it stay?</p>',
    'meta_title' => NULL,
    'meta_description' => NULL,
    'meta_keywords' => NULL,
    'created_at' => '2019-07-21 14:31:12',
    'updated_at' => NULL,
),
));
        
        
    }
}